variable "vpc_name" {}
variable "vpc_cidr" {}
variable "current_region" {}
variable "region_azs" {}
variable "public_subnet_cidrs" {}
variable "private_subnet_cidrs" {}
variable "ubuntu_ami" {}
variable "key_name" {}
variable "ec2_instance_profile" {}